// ORDEN DE VICTOR
// export const SIGN_CLASSES = ['CHAU', 'HOLA', 'COCHABAMBA', 'GRACIAS', 'QUERER', 'AUTO', 'CUAL', 'POR_FAVOR', 'YO', 'CAFE',
//   'COMO_ESTAS', 'ESTOY_BIEN', 'HIJA', 'NOSOTROS', 'TU', 'ABUELO', 'ABUELA', 'BUENAS_NOCHES',
//   'BUENAS_TARDES', 'BUENOS_DIAS', 'MAMA', 'PAPA', 'EL', 'ELLA', 'HIJO'];
  
// ORDEN DE ROYER
export const SIGN_CLASSES = [
  'CHAU',
  'CAFE',
  'HOLA',
  'COCHABAMBA',
  'GRACIAS',
  'QUERER',
  'AUTO',
  'CUAL',
  'POR FAVOR',
  'YO',
  'BUENAS TARDES',
  'BUENOS DIAS',
  'BUENAS NOCHES',
  'MAMA',
  'PAPA',
  'ABUELA',
  'ABUELO',
  'COMO ESTAS',
  'EL',
  'ELLA',
  'ESTOY BIEN',
  'HIJA',
  'HIJO',
  'NOSOTROS',
  'TU',
];